import {APP_NAME, APP_VERSION, DISCLAIMER} from '../constants';
import {BackupFile, VaultData, VaultItem} from '../types';
import {formatDateTime, nowISO} from '../utils/date';

function stripSensitiveItem(item: VaultItem): VaultItem {
  return {
    ...item,
    documentNumberSensitive: undefined,
    notes: item.notes ? '[Excluded from default export]' : undefined,
    frontImageUri: item.frontImageUri ? '[Image stored in app private storage]' : undefined,
    backImageUri: item.backImageUri ? '[Image stored in app private storage]' : undefined,
  };
}

export function createBackup(data: VaultData, includeSensitiveFields: boolean): BackupFile {
  const safeSettings = {
    ...data.settings,
    appLockEnabled: false as const,
    requireUnlockOnLaunch: false as const,
  };
  return {
    appName: APP_NAME,
    appVersion: APP_VERSION,
    exportVersion: 1,
    exportedAt: nowISO(),
    disclaimer: DISCLAIMER,
    encryptedSensitiveFieldsNotice:
      'Vault data is encrypted at rest inside the app. Exported files are not encrypted by PocketVault AI. Protect exported files yourself.',
    items: includeSensitiveFields ? data.items : data.items.map(stripSensitiveItem),
    vehicleProfiles: data.vehicleProfiles,
    carryModes: data.carryModes,
    reminders: data.reminders,
    settings: safeSettings,
    usageEvents: includeSensitiveFields ? data.usageEvents : undefined,
  };
}

export function backupToJson(data: VaultData, includeSensitiveFields: boolean): string {
  return JSON.stringify(createBackup(data, includeSensitiveFields), null, 2);
}

function csvEscape(value: unknown): string {
  const text = value == null ? '' : String(value);
  return `"${text.replace(/"/g, '""')}"`;
}

export function vaultToCsv(data: VaultData): string {
  const rows = [
    ['Title', 'Type', 'Category', 'Issuer', 'Owner', 'Expiration', 'Renewal', 'Favorite', 'Archived'],
    ...data.items.map(item => [
      item.title,
      item.type,
      item.categoryLabel,
      item.issuer ?? '',
      item.ownerName ?? '',
      item.expirationDate ?? '',
      item.renewalDate ?? '',
      item.favorite ? 'Yes' : 'No',
      item.archived ? 'Yes' : 'No',
    ]),
  ];
  return rows.map(row => row.map(csvEscape).join(',')).join('\n');
}

export function generateSafeSummary(data: VaultData): string {
  const lines = [
    'PocketVault AI vault summary',
    `Generated on ${formatDateTime(nowISO())}`,
    '',
    DISCLAIMER,
    '',
    `Items: ${data.items.length}`,
    `Carry modes: ${data.carryModes.length}`,
    `Reminders: ${data.reminders.length}`,
    '',
    'Items',
  ];
  if (data.items.length === 0) {
    lines.push('No vault items have been added.');
  }
  data.items.forEach(item => {
    lines.push(`- ${item.title}`);
    lines.push(`  Type: ${item.type}`);
    lines.push(`  Category: ${item.categoryLabel}`);
    lines.push(`  Issuer: ${item.issuer || 'Not added'}`);
    lines.push(`  Expiration: ${item.expirationDate || 'Not added'}`);
    lines.push(`  Renewal: ${item.renewalDate || 'Not added'}`);
  });
  lines.push('');
  lines.push('Generated by PocketVault AI');
  lines.push(`Generated on ${formatDateTime(nowISO())}`);
  lines.push('This report is for personal reference only and does not replace official documents.');
  return lines.join('\n');
}

export function validateBackup(raw: string): {valid: boolean; message: string; backup?: BackupFile} {
  try {
    const parsed = JSON.parse(raw) as BackupFile;
    if (parsed.appName !== APP_NAME || parsed.exportVersion !== 1) {
      return {valid: false, message: 'This file is not a supported PocketVault AI backup.'};
    }
    if (!Array.isArray(parsed.items) || !Array.isArray(parsed.carryModes)) {
      return {valid: false, message: 'The backup is missing required vault sections.'};
    }
    return {valid: true, message: 'Backup is ready to import.', backup: parsed};
  } catch {
    return {valid: false, message: 'The selected file is not valid JSON.'};
  }
}
